version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - url-shortener-net
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
    networks:
      - url-shortener-net
networks:
  url-shortener-net:
    driver: bridge