apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: url-shortener:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: url-shortener-config
              key: redis-host
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: url-shortener-secret
              key: redis-password
        resources:
          requests:
            cpu: "100m"  # 100 milliCPU (0.1 CPU)
            memory: "128Mi"
          limits:
            cpu: "200m"  # 200 milliCPU (0.2 CPU)
            memory: "256Mi"